import "../globals.css";
import Nav from "../../components/nav";
import Footer from "../../components/footer";

export const metadata = {
  title: "web trang suc nu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
      <Nav />
      {children}
      <Footer />
    </div>

  )
}
