import "../globals.css";
import Nav from "../../components/nav";
import Footer from "../../components/footer";
import Providers from "../../store/Providers";

export const metadata = {
  title: "web trang suc nu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Nav />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
