import "../globals.css";
import Nav from "../../components/nav";
import Footer from "../../components/footer";
import ChatBox from "../../components/chatBox";

export const metadata = {
  title: "web trang suc nu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div >
      <Nav />
      <ChatBox />
      {children}
      <Footer />
    </div>
  );
}
