import { ReduxProvider } from "../../../redux/provider";
import "../../globals.css";
import Nav from "../components/nav";
export const metadata = {
  title: "web trang suc nu",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <div className="  w-screen h-screen flex flex-row bg-[#9B8D6F] p-[15px]">
      <Nav />
      <ReduxProvider>{children}</ReduxProvider>
    </div>
  );
}
