import "../../globals.css";


export const metadata = {
    title: "web trang suc nu",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <div>

            {children}

        </div>

    )
}
