import { ReduxProvider } from "../redux/provider";
import "./globals.css"; // hoặc đường dẫn đúng tới file

export const metadata = {
  title: "web trang suc nu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
