import Providers from '../store/Providers'

export const metadata = {
  title: "web trang suc nu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
            {children}
        </Providers>
    </body>
    </html>
  )
}