import '../../globals.css'

export const metadata = {
  title: "Dang nhap",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
      {children}
    </div>
  )
}