import "../../../../globals.css";
export const metadata = {
  title: "web trang suc nu",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return <div className="w-full h-full px-[7px]">{children}</div>;
}
